api = "0.2"

[buildpack]
  id = "paketo-buildpacks/httpd"
  name = "Apache HTTP Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/httpd"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "httpd"
    name = "Apache HTTP Server"
    sha256 = "e049a2fbeae9614ed1617e183b8f7e185706645299ad853699d6bd357aae1be5"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.43.tar.bz2"
    source_sha256 = "a497652ab3fc81318cdc2a203090a999150d86461acff97c1065dc910fe10f43"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.43_linux_x64_cflinuxfs3_e049a2fb.tgz"
    version = "2.4.43"

  [[metadata.dependencies]]
    id = "httpd"
    name = "Apache HTTP Server"
    sha256 = "ead6e42f2a567ee474fe5000a561def89b57be4b71351d5930445689da83f452"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.46.tar.bz2"
    source_sha256 = "740eddf6e1c641992b22359cabc66e6325868c3c5e2e3f98faf349b61ecf41ea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.46_linux_x64_cflinuxfs3_ead6e42f.tgz"
    version = "2.4.46"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
  mixins = ["libexpat1"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
