api = "0.4"

[buildpack]
  id = "paketo-buildpacks/httpd"
  name = "Paketo Apache HTTP Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/httpd"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "httpd"
    name = "Apache HTTP Server"
    sha256 = "ead6e42f2a567ee474fe5000a561def89b57be4b71351d5930445689da83f452"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.46.tar.bz2"
    source_sha256 = "740eddf6e1c641992b22359cabc66e6325868c3c5e2e3f98faf349b61ecf41ea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.46_linux_x64_cflinuxfs3_ead6e42f.tgz"
    version = "2.4.46"

  [[metadata.dependencies]]
    id = "httpd"
    name = "Apache HTTP Server"
    sha256 = "b86339e20cf93999f1120b9b4e7f089ced9ea007c9c041772d4dd6761c91ef8c"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.48.tar.bz2"
    source_sha256 = "1bc826e7b2e88108c7e4bf43c026636f77a41d849cfb667aa7b5c0b86dbf966c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.48_linux_x64_cflinuxfs3_b86339e2.tgz"
    version = "2.4.48"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
  mixins = ["libexpat1"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
